Updated license and copyright years
qiime2/workshop-playbooks pull request #61
Opened 2021-04-29 23:42 UTC by lizgehret

Updated license and copyright header years to include 2021

2021-04-30 00:31 UTC, lizgehret commented
Ran flake8 and made necessary updates.

2021-05-05 23:54 UTC, thermokarst requested changes
Please see my hashpling comments over in https://github.com/qiime2/busywork/pull/125#pullrequestreview-652846448, thanks!

2021-05-06 15:39 UTC, lizgehret reviewed
Moving hashpling to top of script

2021-05-06 15:42 UTC, lizgehret reviewed
Removing line breaks after hashplings

2021-05-06 15:58 UTC, thermokarst requested changes

2021-05-06 15:58 UTC, thermokarst commented on bin/email_sheets.py
> +# !/usr/bin/env python
Minor typo, there is an extra space tucked away in here that should be removed.

```suggestion
#!/usr/bin/env python
```

2021-05-06 15:58 UTC, thermokarst commented on bin/generate_accts.py
> +# !/usr/bin/env python
Same comment as above!

2021-05-06 16:22 UTC, lizgehret reviewed
Removed space typos within hashpling

2021-05-06 16:26 UTC, thermokarst approved these changes
🦖

2021-05-06 16:26 UTC, merged